apiVersion: kustomize.config.k8s.io/v1beta1
namespace: flagger-system
bases:
  - https://raw.githubusercontent.com/fluxcd/flagger/v1.16.1/artifacts/flagger/account.yaml
  - https://raw.githubusercontent.com/fluxcd/flagger/v1.16.1/artifacts/flagger/crd.yaml
  - https://raw.githubusercontent.com/fluxcd/flagger/v1.16.1/artifacts/flagger/deployment.yaml
resources:
  - namespace.yaml
  - traefik-role.yaml
patchesStrategicMerge:
  - patch.yaml
