apiVersion: kustomize.config.k8s.io/v1beta1
namespace: cilium
helmCharts:
- name: cilium
  includeCRDs: true
  releaseName: cilium
  version: 1.10.6
  repo: https://helm.cilium.io/
  namespace: cilium
resources:
  - namespace.yaml
