apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: linkerd2
  repo: https://helm.linkerd.io/stable
  version: 2.11.1
  releaseName: linkerd2
  includeCRDs: true
  namespace: linkerd
  valuesFile: values.yaml
resources:
  - namespace.yaml

