apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/install.yaml
- sealed-secret.yaml
- workflows-sealed-secret.yaml
- ingressroute.yaml
patches:
- path: redis_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-redis
- target:
    kind: Secret
    name: argocd-secret
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-secret-dangling
patchesStrategicMerge:
- server.yaml
- repo-server.yaml
- configmap.yaml
namespace: argocd
