apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-workflows/v3.2.6/manifests/install.yaml
- ingressroute.yaml
patchesStrategicMerge:
- server.yaml
namespace: argocd
