apiVersion: kustomize.config.k8s.io/v1beta1
helmCharts:
- name: linkerd-viz
  repo: https://helm.linkerd.io/stable
  version: 2.11.1
  releaseName: linkerd-viz
  includeCRDs: true
  namespace: linkerd-viz
resources:
  - sealed-secret.yaml
  - ingressroute.yaml
patchesStrategicMerge:
- server.yaml
