apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: production
  source:
    path: overlays/rook-ceph/production
    repoURL: https://gitlab.cryptocat.eu/cryptocat/core.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
