apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: production
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  source:
    path: overlays/sealed-secrets/production
    repoURL: https://gitlab.cryptocat.eu/cryptocat/core.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
