apiVersion: kustomize.config.k8s.io/v1beta1
namespace: traefik
helmCharts:
- name: traefik
  includeCRDs: true
  releaseName: traefik
  version: 10.9.1
  repo: https://helm.traefik.io/traefik
  namespace: traefik
  valuesInline:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      traefik:
        port: 9000
        expose: false
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - certificate.yaml
  - ingressroute.yaml

