---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: gitlab
helmCharts:
- name: gitlab
  includeCRDs: true
  valuesInline:
    global:
      edition: ee
      hosts:
        domain: cryptocat.eu
      ingress:
        enabled: false
        configureCertmanager: false
      initialRootPassword: {
        "secret": "gitlab-root-password",
        "key": "password"
        }
    certmanager:
      installCRDs: false
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      install: false
  releaseName: gitlab
  version: 5.6.0
  namespace: gitlab
  repo: https://charts.gitlab.io/
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - ingressroute.yaml
