apiVersion: kustomize.config.k8s.io/v1beta1
namespace: metrics-server
bases:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.2/components.yaml
resources:
  - namespace.yaml
patchesStrategicMerge:
  - patch.yaml
