apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
spec:
  acme:
    email: "info@cryptocat.eu"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "letsencrypt-live-account-key"
    solvers: [{'dns01': {'cloudflare': {'email': 'cloudflare@cryptocat.eu', 'apiTokenSecretRef': {'name': 'cloudflare-api-token-secret', 'key': 'api-key'}}}}]
